# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.eu.mailgun.org:2525
mail_admin: admin@espaciosutil.org
mail_hostname: espaciosutil.org
mail_user: wordpress@espaciosutil.org
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
