matomo_enabled: true

matomo_site_hosts:
  - matomo.espaciosutil.test

matomo_db_host: 127.0.0.1
matomo_db_password: "{{ vault_matomo_db_password }}"

matomo_admin_email: analytics@espaciosutil.org
matomo_admin_password: "{{ vault_matomo_admin_password }}"

matomo_use_https: false
matomo_use_letsencrypt: false

matomo_cli_install: true
matomo_cli_manage_sites: true

matomo_archive_url: "http://matomo.espaciosutil.test"

matomo_sites:
  - name: "Espacio Sutil (development)"
    url: "http://espaciosutil.test"
    slug: espaciosutil-development
