# Created by trellis-cli v1.14.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  espaciosutil.org:
    site_hosts:
      - canonical: espaciosutil.org
        redirects:
          - www.espaciosutil.org
    local_path: ../site
    branch: main
    repo: git@github.com:aitormendez/espaciosutil.org.git
    repo_accepts_https: true
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
      duration: 30s
      skip_cache_uri: >-
        /wp-admin/|/wp-json/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml|
        /login/|/cuenta-de-membresia/|/pago-de-membresia/|/confirmacion-de-membresia/
      skip_cache_cookie: >-
        comment_author|wordpress_[a-f0-9]+|wordpress_sec_[a-f0-9]+|wp-postpass|
        wordpress_no_cache|wordpress_logged_in
    env:
      db_host: 127.0.0.1
