# Created by trellis-cli v1.14.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  espaciosutil.org:
    site_hosts:
      - canonical: stage.espaciosutil.org
    local_path: ../site
    branch: main
    repo: git@github.com:aitormendez/espaciosutil.org.git
    repo_accepts_https: true
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
