# Created by trellis-cli v1.14.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  espaciosutil.org:
    site_hosts:
      - canonical: stage.espaciosutil.org
    local_path: ../site
    branch: codex/espacio-sutil-staging
    repo: git@github.com:aitormendez/espaciosutil.org.git
    repo_accepts_https: true
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    env:
      db_host: 127.0.0.1
      db_user_host: 127.0.0.1
      disable_wp_cron: true
      transactional_email_from: staging@invalid.example
      transactional_email_name: Espacio Sutil
